# Generated by Django 4.2.30 on 2026-05-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_poste', models.CharField(choices=[('Manager', 'Manager'), ('Développeur', 'Développeur'), ('RH', 'RH'), ('Commercial', 'Commercial'), ('Autre', 'Autre')], max_length=50)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_embauche', models.DateField()),
                ('dernier_diplome', models.CharField(max_length=100)),
                ('est_archive', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='hr_app.departement')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dirige', to='hr_app.employe'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage')], max_length=20)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='hr_app.employe')),
            ],
        ),
    ]
